# Generated by Django 4.2.29 on 2026-03-31 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contactmessage_order_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('luxury_perfumes', 'Luxury Perfumes'), ('arabian_perfumes', 'Arabian Perfumes'), ('body_mists', 'Body Mists'), ('gift_products', 'Gift Products')], default='luxury_perfumes', max_length=20),
        ),
    ]
