# Generated by Django 4.2.29 on 2026-04-02 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_product_product_type_alter_product_size_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('designer_perfumes', 'Designer Perfumes'), ('arabian_perfumes', 'Arabian Perfumes'), ('body_mists', 'Body Mists'), ('gift_products', 'Gift Products'), ('car_fresheners_and_oil_perfumes', 'Car Fresheners and Oil Perfumes')], default='designer_perfumes', max_length=35),
        ),
    ]
