# Generated by Django 4.2.29 on 2026-04-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('designer_perfumes', 'Designer Perfumes'), ('arabian_perfumes', 'Arabian Perfumes'), ('body_mists', 'Body Mists'), ('gift_products', 'Gift Products'), ('car_fresheners', 'Car Fresheners'), ('oil_perfumes', 'Oil Perfumes')], default='designer_perfumes', max_length=35),
        ),
    ]
