# Generated by Django 4.2.29 on 2026-04-14 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google', 'Google'), ('facebook', 'Facebook'), ('apple', 'Apple'), ('github', 'GitHub'), ('twitter', 'Twitter'), ('linkedin', 'LinkedIn')], max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('client_id', models.CharField(max_length=255)),
                ('secret_encrypted', models.TextField(blank=True)),
                ('key', models.CharField(blank=True, max_length=255)),
                ('redirect_uris', models.TextField(blank=True, help_text='Enter one URI per line.')),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_social_providers', to=settings.AUTH_USER_MODEL)),
                ('sites', models.ManyToManyField(blank=True, to='sites.site')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_social_providers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Social Provider',
                'verbose_name_plural': 'Social Providers',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
    ]
