# Generated by Django 4.2.29 on 2026-04-14 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialProvider',
        ),
    ]
